version: 2
jobs:
  build-linux:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Env Setup
          command: |
            lsb_release -a
            sudo apt-get update
            sudo apt-get install -qq pkg-config fuse
            sudo modprobe fuse
            sudo chmod 666 /dev/fuse
            sudo chown root:$USER /etc/fuse.conf
      - run:
          name: Run tests
          command: |
            ./gradlew test
            ./gradlew clean build check
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
  build-win:
    machine:
      image: windows-server-2019-vs2019:current
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Env Setup
          command: |
            choco install winfsp
      - run:
          name: Run tests
          command: |
            ./gradlew.bat test
            ./gradlew.bat clean build check
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Env Setup
          command: |
            brew install --cask osxfuse
      - run:
          name: Run tests
          command: |
            ./gradlew test
            ./gradlew clean build check
workflows:
  version: 2
  workflow:
    jobs:
      - build-linux
#      - build-macos
#      - build-win
